### PR TITLE
use the Oracle PList format if the JVM Version is at least 1.7

### PR DESCRIPTION
**Pull request by Vampire**
As far as I remember I've submitted this against 2.3.1 already.
But I guess Will didn't have time to maintain the project anymore which is why you overtook it.
So here again, this time as PR. :-)

### CODE REVIEW

**Comment by tofi86** [comment]
I have a big problem with this PR by @Vampire, merged by @tobium.

First of all it doesn't support Java 9 or Java 10 (see review comments).

And secondly it doesn't allow the property `useJavaXKey` anymore to be used with Java 1.7 or 1.8
 All the sense of this function was to provide the same possibilities of the old Apple `Java` Plist key for newer Java version like 1.8 and above because the Oracle Plist format is insufficient.

When I previously used `jvmversion="1.7" useJavaXKey="true"` in my buildfile the PList created looked like:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
  <dict>
    <key>CFBundleName</key>
    <string>pagina EPUB-Checker</string>
    <key>CFBundleShortVersionString</key>
    <string>1.7.2</string>
    <key>CFBundleAllowMixedLocalizations</key>
    <string>true</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleExecutable</key>
    <string>universalJavaApplicationStub</string>
    <key>CFBundleDevelopmentRegion</key>
    <string>German</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>PAEC</string>
    <key>CFBundleVersion</key>
    <string>1.7.2_ee71a</string>
    <key>CFBundleIconFile</key>
    <string>paginaEPUBChecker_1024.icns</string>
    <key>CFBundleIdentifier</key>
    <string>de.paginagmbh.epubchecker</string>
    <key>NSHumanReadableCopyright</key>
    <string>© 2010-2018 pagina GmbH, Tübingen, Germany</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key>
        <string>EPUB files</string>
        <key>CFBundleTypeRole</key>
        <string>Viewer</string>
        <key>CFBundleTypeExtensions</key>
        <array>
          <string>epub</string>
          <string>EPUB</string>
        </array>
      </dict>
    </array>
    <key>JavaX</key>
    <dict>
      <key>MainClass</key>
      <string>de.paginagmbh.epubchecker.PaginaEPUBChecker</string>
      <key>JVMVersion</key>
      <string>1.7</string>
      <key>ClassPath</key>
      <array>
        <string>$JAVAROOT/paginaEPUBChecker.jar</string>
      </array>
      <key>SplashFile</key>
      <string>SplashScreen_Mac.png</string>
    </dict>
  </dict>
</plist>
```

Now if I use the same buildfile but remove the `useJavaXKey` attribute, the build file is missing essential details:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CFBundleName</key>
    <string>pagina EPUB-Checker</string>
    <key>CFBundleShortVersionString</key>
    <string>1.7.2</string>
    <key>CFBundleAllowMixedLocalizations</key>
    <string>true</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleExecutable</key>
    <string>universalJavaApplicationStub</string>
    <key>CFBundleDevelopmentRegion</key>
    <string>German</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>PAEC</string>
    <key>CFBundleVersion</key>
    <string>1.7.2_ee71a</string>
    <key>CFBundleIconFile</key>
    <string>paginaEPUBChecker_1024.icns</string>
    <key>CFBundleIdentifier</key>
    <string>de.paginagmbh.epubchecker</string>
    <key>NSHumanReadableCopyright</key>
    <string>© 2010-2018 pagina GmbH, Tübingen, Germany</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>CFBundleDocumentTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeName</key>
        <string>EPUB files</string>
        <key>CFBundleTypeRole</key>
        <string>Viewer</string>
        <key>CFBundleTypeExtensions</key>
        <array>
          <string>epub</string>
          <string>EPUB</string>
        </array>
      </dict>
    </array>
    <key>JVMMainClassName</key>
    <string>de.paginagmbh.epubchecker.PaginaEPUBChecker</string>
  </dict>
</plist>
```

Where is the classpath entry? where is the JVMVersion key? where the splashscreen key?

This PullRequest is completely broken and needs to be reworked before ever released as version 3.4.0!

ToDo's:
- [ ] The JavaX-key feature needs to stay supported even when Java version is higher than 1.7
- [ ] The Oracle Plist format generated by this PR needs to be fixed
- [ ] Support for Java 9 and 10 needs to be added

Is anyone still maintaining this project? @tobium?

Best,
Tobias

**Comment by tofi86** [comment]
>  The JavaX-key feature needs to stay supported even when Java version is higher than 1.7

So we obviously need a switch for that!

**Comment by Vampire** [comment]
It is not "obvious" that this is necessary or that anyone is broken.
If you think something needs changed, stop ranting and open a PR, but research properly first.
That Java 9 and 10 is "not supported" has nothing to do with this PR, they didn't even exist when this PR was created.

Why should `useJavaXKey` be supported?
It is not used, it has absolutely no meaning to Oracle Java (except something changed).
Only the Apple-own Java which was used up to 1.6 had the old format with the `useJavaXKey` support.
From 1.7 on Apple does not do their own Java anymore and the Oracle Java does not support that key and the old format, but the new format.

This PR is not "completely broken" but works fine in productive use.
Maybe not with 9 or 10, I didn't test with those, but it works perfectly fine with 8 and 9.

**Comment by tofi86** [comment]
Sorry, this wasn’t meant to be rude.

I will send a PR with changes to the Oracle format feature introduced by you.

And I will clarify the state of the `JavaX` key feature which is still important.

Best,
Tobias

**Comment by Vampire** [comment]
But what for?
At least when I implemented this, the JavaX key was not evaluated by Oracle Java as far as I remember.
And the resulting bundle with my PR applied is not broken but working exactly like expected (with Java 8 that is).

**Comment by tofi86** [comment]
The JavaX key isn't standardized. It's supported by https://github.com/tofi86/universalJavaApplicationStub (~100 stars, ~30 clones a day), a project I created when Oracle took over Java development from Apple. The purpose was, that there is a launcher stub supporting the "old" `Java` key even on Java 7 and 8.
Then with Java 8 Oracle started showed warning messages, redirecting Apps using the `Java` key to the old Java 6. Together with the original developer of JarBundler we came up with the idea of using a non-standard key named `JavaX` and I did implementation in both projects (first in my fork, then merged here)

Why? Because the "new" Oracle Plist keys doesn't support all the features the Apple dictionary did. Call it "legacy" mode.

That's why the `useJavaXKey` attribute exists.

And quite a bunch of tools use this feature frequently! https://github.com/search?q=usejavaxkey&type=Code

We cannot just drop support for it.

**Comment by tofi86** [comment]
I added PR #12 and wrote a short guide to what I did and why. Hope this helps! :-)

Have a nice weekend, guys!

**Pull request merged**
