### PR TITLE
Add support for NSSupportsAutomaticGraphicsSwitching with true as default or the battery is drained unnecessarily as high-performance mode is enforced

### PR DESCRIPTION
**Pull request by Vampire**
More information can be found at https://sourceforge.net/p/jedit/feature-requests/529/ and the three issues linked there

### CODE REVIEW

**Review by tofi86 — APPROVED** [review]
Looks good to me!

**Comment by tofi86** [comment]
@slajar could you also take a look at this and merge it, once the revert #17 is merged? Thanks :-)

**Comment by slajar** [comment]
anything new here?

**Comment by Vampire** [comment]
What new do you expect? I created this PR 2 years ago, it was approved 2 years ago and it still waits to be merged.

**Comment by tobium** [comment]
could you pls. resolve the merge conflict?

**Comment by tofi86** [comment]
I'll rebase and merge.

**Pull request merged**
